### ISSUE TITLE
[Feature] - OH-58D Support

### ISSUE THREAD

**Issue by Stains02** [FalcoGer/CoordinateConverter#13]
My Apache squadron are heavy users of CoordinateConverter for our missions and training. We recently added a Kiowa troop and would love the ability to use CC with the new aircraft. I'm aware that the Kiowa comes with some DTC functionality, but we really like CC and would enjoy a unified interface for all our planning. Thanks!

**Comment by FalcoGer** [comment]
Don't have it and don't plan on buying it. Feel free to make a pull request.

**Comment by kkernan** [comment]
@jamesamckenzie I have the OH-58D. I'll take a stab at adding support for it, maybe you can help debug. I took a look at adding the F15E but kind of bailed when all the Razbam stuff happened.

**Comment by FalcoGer** [comment]
@kkernan I recently added a feature where you can run a lua script from the program inside DCS. That might help you debug things.
There is the [DebugCommandList](https://github.com/FalcoGer/CoordinateConverter/blob/master/CoordinateConverter/DCS/Communication/DebugCommandList.cs), which will execute DCS button presses as you add them, so you can step through your code.
If you need help with integration, poke me on Discord `falcoger`

**Comment by kkernan** [comment]
I think I have this 90% finished. Currently this code
```
public bool? IsPilot {
	get
	{
		DCSMessage message = new DCSMessage()
		{
			GetHandleData = new List<string>()
			{
				"SEAT"
			},
		};
		message = DCSConnection.SendRequest(message);
		if (message != null && message.HandleData.ContainsKey("SEAT"))
		{
			isPilot = message.HandleData["SEAT"] == "0";
		}

		return isPilot;
	} private set
	{
		isPilot = value;
	}
}
```
which for the Apache seems to give you the seat position always returns true for the Kiowa regardless of the seat you are in. Any thoughts on how I would see if that data is exported for the Kiowa? If not, I'm half temped to just always enter the data from the CPG seat rather than reintroduce the seat selection dialogue. In the case of the Kiowa there is only the one keyboard being shared anyhow.

**Comment by FalcoGer** [comment]
Completed. Thanks @kkernan / SPU
