### ISSUE TITLE
Getting norton data protection error when try to run program

### ISSUE THREAD

**Issue by efgross** [FalcoGer/CoordinateConverter#17]
Just installed and Norton AV won't open program due to data protector is blocking it, even with it excluded.  Tried the .msi and the manual install versions.

![Coordinate Converter Norton error](https://github.com/user-attachments/assets/183e3f1e-d7fd-4350-96db-b920be9c62d5)

**Comment by FalcoGer** [comment]
Install coordinate converter somewhere where it has write access with your user's permission. for example %appdata%/CoordinateConverter, not C:/Program Files.
It's crashing because it tries to create a configuration file in it's current directory, but it can't write to it. Windows tries to generate an error report. Why norton blocks that, I have no idea.
Alternatively wait for the next release. I'm going to fix this right now since it seems to be a problem that multiple people have (not norton, but the config file thing).
Alternatively run as admin, but I don't recommend that.

**Comment by FalcoGer** [comment]
@efgross did that fix your issue?
